version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # CORRIGIDO: Mapeando a porta 5050 do host para a porta 5050 do contêiner da sua aplicação
    ports:
      - "5050:5050"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_notas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgre
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: lV/C9+E0ZpA7xYj2kM5uPz2QxT7b8A0X3jF6vS4yR1wW5uV0Q8vA3eP4oG7qI2hL3mN5pQ6rS7tU8vW9xY0z=
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: db_notas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432" # Opcional, apenas se precisar acessar o DB diretamente de fora do Docker
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    # CORRIGIDO: Mapeando a porta 5051 do host para a porta 80 do contêiner pgAdmin
    ports:
      - "5051:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data: